name: Deploy using AWS SSM Send-Command 

on:
  push:
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: AWS SSM Send Command
      uses: peterkimzz/aws-ssm-send-command@1.0.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        instance-ids: ${{ secrets.INSTANCE_ID }}
        comment: Deploy the master branch
        working-directory: /
        command: /bin/sh ./deploy.sh

# The Secrets we provided to the repo earlier come into use in this script.

# There are 3 parts of the .yml file to configure:
# 1. The aws-region should be the same region as where you have created your EC2 instance. (If you do not know, check the top left of your EC2 console to confirm the region you are in).
# 2. working-directory should be the directory where you created the deploy.sh script.
# 3. command should be the command you would like the SSM agent to run.

# Once this is complete, commit and push the workflow to your repo.
